# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('_ext'))


# -- Project information -----------------------------------------------------

project = 'Mapflow'
copyright = '2021-2025, Geoalert'
author = 'Geoalert'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
  'edit_on_github',
  'sphinxemoji.sphinxemoji',
  'sphinx_rtd_theme',
  'sphinxnotes.strike',
  'sphinx_favicon',
  'notfound.extension'
]


favicons = [
   {
      "sizes": "16x16",
      "href": "https://mapflow.ai/favicon/favicon-16x16.png",
   },
   {
      "sizes": "32x32",
      "href": "https://mapflow.ai/favicon/favicon-32x32.png",
   },
   {
      "rel": "apple-touch-icon",
      "sizes": "180x180",
      "href": "apple-touch-icon.png",  # use a local file in _static
   },
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

version = '0'

html_theme_options = {
    'display_version': False,
    'logo_only': True
}
html_logo = '_static/logo_mapflow.png'

# To show the same sidebar for each page.
# NOTE: sphinx_rtd_theme builds its own sidebar and ignores html_sidebars, so this
# is effectively inert. `versions.html` (the language switcher) is rendered by the
# theme's layout.html instead, which is why it must NOT be listed here — doing so
# would render it twice under themes that do honour html_sidebars.
html_sidebars = {
    '**': [
        'globaltoc.html',
        'relations.html',
        'sourcelink.html',
        'searchbox.html',
    ]
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = ['globals.css']

# -- 404 Page Configuration --------------------------------------------------
# The 404 page is generated by sphinx-notfound-page.
html_additional_pages = {}

# Configure sphinx-notfound-page extension
notfound_urls_prefix = ''  # Use relative URLs (works with multi-language builds)
notfound_template = '404.html'
notfound_context = {
    'title': 'Page Not Found',
    'body': '<h1>404 - Page Not Found</h1>',
}

# -- Options for Edit on github ----------------------------------------------
edit_on_gitlab_user = 'geoalert'
edit_on_github_branch = 'main/source'

# -- Internationalization options --------------------------------------------
locale_dirs = ['locale/']   # path is example but recommended.
gettext_compact = False     # optional: creates separate PO files for each RST file

# Default language. Overridden per build with `sphinx-build -D language=ru ...`.
language = 'en'

# The language served from the site root, without a /<lang>/ prefix.
# https://docs.mapflow.ai/index.html is English; other languages live under
# https://docs.mapflow.ai/<lang>/index.html
root_language = 'en'

# Single source of truth for the language switcher: (display name, language code).
# Only list languages that are actually built and deployed — every entry here
# becomes a clickable option in the switcher.
#
# To add a language:
#   1. add it to this list
#   2. `sphinx-intl update -p source/locale -l <code>` and translate the PO files
#   3. add a build target to `Makefile` (build-all) and `build_all_languages.sh`
languages = [
    ('English', 'en'),
    ('Русский', 'ru'),
    ('Español', 'es'),
    ('中文', 'zh'),
    # ('Deutsch', 'de'),
    # ('Français', 'fr'),
]

# gettext options
gettext_uuid = True  # Generate UUIDs for each translatable message
gettext_auto_build = True  # Automatically compile PO to MO files

html_context = {
    'languages': languages,
    'root_language': root_language,
    # Placeholder — the real value is filled in by setup() below, because at this
    # point `language` is still the default and does not reflect `-D language=...`.
    'current_language': language,
}


def setup(app):
    """Keep html_context in sync with the language actually being built.

    conf.py is evaluated *before* Sphinx applies command-line overrides, so
    `current_language` captured above is always 'en'. Without this hook the
    Russian build renders a switcher that thinks it is on the English page:
    English stays selected and the URL rewrite targets the wrong prefix.
    """

    def _sync_language(app, config):
        context = config.html_context
        context['current_language'] = config.language or root_language
        context['language_codes'] = [code for _name, code in context['languages']]

    app.connect('config-inited', _sync_language)
